### PR TITLE
Pass shots to IonQ API

### PR DESCRIPTION
**Pull request by dabacon**
Shots were not being passed to the API, causing all jobs to run 100 shots, the IonQ Default.

I did not see a test of the request structure, let me know if you'd like me to try to add one.

Also not sure on your style for wrapping, so feel free to nit :)

### CODE REVIEW

**Comment by josh146** [comment]
Thanks for catching this @dabacon! I'll set aside some time a bit later today to go through it thoroughly.

Two thoughts:

- I'm somewhat surprised the plugin was reliably passing our integration tests, as some of them require minimum 1000 shots for a small enough variance 🤔 

- We really need to come up with a better CI strategy that does not rely on secret environment variables 🙈

**Comment by josh146** [comment]
Hi @dabacon, I've just pushed a few commits that do the following:

- Enable the unit tests to pass on forked PRs 🎉 
- Disable the integration tests on forked PRs for now (will still need to come up with a better solution here).
- Have added a test to ensure that shots are correctly specified when submitting a job to the API.

Let me know if you have any thoughts or comments, otherwise this should be ready for merging in :)

**Review by dabacon — COMMENTED** [review]
Awesome thanks for adding the test.  These api tests with mocking are never much fun to write :)

**Comment by josh146** [comment]
> These api tests with mocking are never much fun to write :)

That is true 😆 Took me longer than I expected it to take, I must admit

**Pull request merged**
