### PR TITLE
Allow overriding target on device

### PR DESCRIPTION
**Pull request by Cynocracy**
Alternative to https://github.com/PennyLaneAI/PennyLane-IonQ/pull/49 for supporting more targets.

### CODE REVIEW

**Comment by Cynocracy** [comment]
Ready for review!

**Comment by josh146** [comment]
Thanks @Cynocracy! I've tagged @albi3ro to have a look

**Review by antalszava — APPROVED** [review]
Looks good, thank you! :100: The integration tests execute well locally except for 2 tests. The issues are, however, unrelated to the changes in this PR as they seem to fail on `master` too.

**Comment by antalszava** [comment]
Overriding the check as the coverage matches the coverage on `master` locally.

**Comment by Cynocracy** [comment]
Thank you!

**Pull request merged**
