### PR TITLE
Add Harmony backend for IonQ

### PR DESCRIPTION
**Pull request by Cynocracy**

### CODE REVIEW

**Comment by albi3ro** [comment]
Hi @Cynocracy  and thanks for opening a PR.

Could you provide some information about what you are wanting to achieve with this PR?

You may also need to upgrade your version of black and use the `-l 100` line length specification. In the most recent version, the formatting of `a ** b` changed to `a**b`.

**Comment by Cynocracy** [comment]
Thank you! Will update and do another formatting pass

**Comment by albi3ro** [comment]
Was something about `qml.device('ionq.qpu', target='qpu.harmony', wires=wires)` not working?

Does this PR just make it slightly easier to create, fixing something that was broken, or add a new feature?

**Comment by Cynocracy** [comment]
That method works fine for now, but we're working on new QPU backend targets, and thought it would map more cleanly into pennylane by adding support here.

Are there any reasons to prefer having support in Pennylane itself for different sized QPU backends?

If not, I can scrap this PR and keep with the target="" approach

**Comment by Cynocracy** [comment]
Tested out that arg, it doesn't seem like we're able to send it through the qml device like you mentioned.

I would think that would work for us though, perhaps it's just some missing wiring?

**Comment by Cynocracy** [comment]
Cut https://github.com/PennyLaneAI/PennyLane-IonQ/pull/50 as an alternative to this approach

**Comment by Cynocracy** [comment]
Aye aye! I don't mind closing this in favor of https://github.com/PennyLaneAI/PennyLane-IonQ/pull/50 will comment over there when ready for review, am not sure why the tests are failing.

**Pull request closed without merging**
